export const SET_CURRENT_USER       = 'SET_CURRENT_USER';
export const TOGGLE_SUGGESTIONS     = 'TOGGLE_SUGGESTIONS';
export const UPDATE_SEARCH_RESULTS  = 'UPDATE_SEARCH_RESULTS';
export const UPDATE_SELECTED_RESULT = 'UPDATE_SELECTED_RESULT';
